version: '2'
services:
  api:
    build: ./
    command: node app.js
    restart: always
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis
    ports:
      - "8001:6379"